FROM docker.io/alpine:latest

#RUN echo "https://mirrors.aliyun.com/alpine/latest-stable/main" > /etc/apk/repositories
#RUN echo "https://mirrors.aliyun.com/alpine/latest-stable/community" >> /etc/apk/repositories

RUN apk add --update \
	bash
